Blogger/Controllers/BlogPostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Blogger.Helpers;
using Blogger.Models;

namespace Blogger.Controllers
{
    public class BlogPostsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: BlogPosts
        public ActionResult Index()
        {
            return View(db.Blogs.ToList());
        }

        // GET: BlogPosts/Details/5
        public ActionResult Details(string slug)
        {
            if (slug == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPosts blogPosts = db.Blogs.FirstOrDefault(b => b.Slug == slug);
            if (blogPosts == null)
            {
                return HttpNotFound();
            }
            return View(blogPosts);
        }


        // GET: BlogPosts/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: BlogPosts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Title,Abstract,BlogBody,Photo,Published")] BlogPosts blog, HttpPostedFileBase photo)
        {
            if (ModelState.IsValid)
            {
                
                if (ImageUploadValidator.IsWebFriendlyImage(photo))
                {
                    var fileName = Path.GetFileName(photo.FileName);
                    fileName = Path.GetFileNameWithoutExtension(fileName) + "_" + DateTime.Now.Ticks + Path.GetExtension(fileName);
                    photo.SaveAs(Path.Combine(Server.MapPath("~/Uploads/"), fileName));
                    blog.Photo = "/Uploads/" + fileName;
                }


                var Slug = StringUtilities.URLFriendly(blog.Title);
                if (String.IsNullOrWhiteSpace(Slug))
                {
                    ModelState.AddModelError("Title", "Invalid Title");
                    return View(blog);
                }
                if (db.Blogs.Any(p => p.Slug == Slug))
                {
                    ModelState.AddModelError("Title", "Title must be unique");
                    return View(blog);
                }

                blog.Slug = Slug;
                blog.Created = DateTime.Now;
                db.Blogs.Add(blog);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(blog);
        }

        // GET: BlogPosts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPosts blogPosts = db.Blogs.Find(id);
            if (blogPosts == null)
            {
                return HttpNotFound();
            }
            return View(blogPosts);
        }

        // POST: BlogPosts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Abstract,BlogBody,Photo,Slug,Created,Published")] BlogPosts blog, HttpPostedFileBase photo)
        {
            if (ModelState.IsValid)
            {
                blog.Updated = DateTime.Now;
                db.Entry(blog).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(blog);
        }

        // GET: BlogPosts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPosts blogPosts = db.Blogs.Find(id);
            if (blogPosts == null)
            {
                return HttpNotFound();
            }
            return View(blogPosts);
        }

        // POST: BlogPosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BlogPosts blogPosts = db.Blogs.Find(id);
            db.Blogs.Remove(blogPosts);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Blogger/Views/Shared/_CreateBlogPartial.cshtml
@model Blogger.Models.BlogPosts

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "BlogPosts", FormMethod.Post, new { @enctype = "Multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>BlogPosts</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Abstract, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Abstract, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Abstract, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BlogBody, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BlogBody, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BlogBody, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="photo" class="form-control" />
                @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Published, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Published)
                    @Html.ValidationMessageFor(model => model.Published, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

Blogger/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <title>Blogger</title>


    <link href="~/Content/PagesList.css" rel="stylesheet" />
    <link href="~/CSS/carouFredSel.css" rel="stylesheet" />
    <link href="~/CSS/clear.css" rel="stylesheet" />
    <link href="~/CSS/common.css" rel="stylesheet" />
    <link href="~/CSS/font-awesome.min.css" rel="stylesheet" />
    <link href="~/CSS/sm-clean.css" rel="stylesheet" />
    <link href="~/CSS/style.css" rel="stylesheet" />
</head>
<body class="home blog">
    <!-- Preloader Gif -->
    <table class="doc-loader">
        <tbody>
            <tr>
                <td>
                    <img src="~/Images/ajax-document-loader.gif" alt="Loading...">
                </td>
            </tr>
        </tbody>
    </table>

    <!-- Left Sidebar -->
    <div id="sidebar" class="sidebar">
        <div class="menu-left-part">
           
            <div class="search-holder">
                    <label>
                        @using (Html.BeginForm("Index", "Home", FormMethod.Get, htmlAttributes: new { @class = "form" }))
                        {
                        <input type="search" class="search-field" placeholder="Type here to search..." id="serachStr" name="searchStr" title="Search for:">
                          }
                    </label>
            </div>

            <div class="site-info-holder">
                <h1 class="site-title">Blogger</h1>
                <p class="site-description">
                    A place where I can share my ideas and thoughts with the world..
                </p>
            </div>
            <nav id="header-main-menu">
                <ul class="main-menu sm sm-clean">
                    <li><a href=@Url.Action("Index","Home") class="current">Home</a></li>
                    @if (User.IsInRole("Admin"))
                    {
                    <li><a href=@Url.Action("Create","BlogPosts")>Create Blog</a></li>

                    }
                    <li><a href=@Url.Action("About","Home")>About Me</a></li>
                    <li><a href=@Url.Action("Index","BlogPosts")>View All Blogs</a></li>
                    <li><a href=@Url.Action("Contact","Home")>Contact</a></li>
                </ul>
            </nav>
            <footer>
                <div class="footer-info">
                    © 2019 SUPPABLOG HTML TEMPLATE. <br> MODIFIED BY <a href="https://gjzport.azurewebsites.net/" target="_blank">GREG ZAMBRANA</a>.
                </div>
            </footer>
        </div>
        <div class="menu-right-part">
            <div class="logo-holder">
                <a href=@Url.Action("Index","Home")>
                    <img src="~/Images/logo.png" alt="Suppablog WP">
                </a>
            </div>
            <div class="toggle-holder">
                <div id="toggle">
                    <div class="menu-line"></div>
                </div>
            </div>
            <div class="social-holder">
                <div class="social-list">
                    <a href="https://github.com/Greg712144" target="_blank"><i class="fa fa-github-square"></i></a>
                    <a href="https://www.linkedin.com/in/gregorio-zambrana-5873a8152/" target="_blank"><i class="fa fa-linkedin-square"></i></a>

                </div>
            </div>
            <div class="fixed scroll-top"><i class="fa fa-caret-square-o-up" aria-hidden="true"></i></div>
        </div>
        <div class="clear"></div>
    </div>

    <!-- Home Content -->
    <div id="content" class="site-content">


        @RenderBody()

        <div class="clear"></div>
    </div>




    <script src="~/Javascript/jquery.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Javascript/imagesloaded.pkgd.js"></script>
    <script src="~/Javascript/jquery.nicescroll.min.js"></script>
    <script src="~/Javascript/jquery.smartmenus.min.js"></script>
    <script src="~/Javascript/jquery.carouFredSel-6.0.0-packed.js"></script>
    <script src="~/Javascript/jquery.mousewheel.min.js"></script>
    <script src="~/Javascript/jquery.touchSwipe.min.js"></script>
    <script src="~/Javascript/jquery.easing.1.3.js"></script>
    <script src="~/Javascript/main.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>